### ISSUE TITLE
openCoverSummary. System.ArgumentException: The input sequence is empty

### ISSUE THREAD

**Issue by IgorBuchelnikov** [SteveGilham/altcover#116]
Exception in altcover while executing:

`
dotnet test --filter Name~Minim  /p:AltCover=true /p:AltCoverStrongNameKey=assembly_strong_name_key.snk /p:DefineConstants=GeneratingMinimalTestsToCover
`

```
System.ArgumentException: The input sequence is empty. (Parameter 'source')
   at Microsoft.FSharp.Collections.SeqModule.Head[T](IEnumerable`1 source) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 1364
   at AltCover.Runner.I.openCoverSummary(XDocument report) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 352
   at AltCover.Runner.I.covered@447.Invoke(XDocument report) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 447
   at AltCover.Runner.I.standardSummary(XDocument report, ReportFormat format, Int32 result) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 446
   at AltCover.Runner.declareOptions@497.Invoke(XDocument report, ReportFormat format, Int32 result) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 497
   at AltCover.Runner.J.doSummaries@878-1.Invoke(FSharpFunc`2 summary) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 878
   at Microsoft.FSharp.Collections.ListModule.Fold[T,TState](FSharpFunc`2 folder, TState state, FSharpList`1 list) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\list.fs:line 222
   at AltCover.Runner.J.doSummaries(XDocument document, ReportFormat format, Int32 result) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 877
   at AltCover.Runner.value@909-3.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover.Engine\Runner.fs:line 936
   at AltCover.CommandLine.I.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover.Engine\CommandLine.fs:line 206
ParamName = 
"source"
TargetSite = 
T Head[T](System.Collections.Generic.IEnumerable`1[T])
Data = 
seq []
InnerException = 
<null>
HelpLink = 
<null>
Source = 
"FSharp.Core"
HResult = 
-2147024809
```

**Comment by SteveGilham** [comment]
That's saying that the coverage file generated is missing all its `<Summary>` records; in particular, the top level one with the overall coverage values (which are about to be echoed to the output) is not there.  The file should look like
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<CoverageSession xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Summary numSequencePoints="49" visitedSequencePoints="11" numBranchPoints="38" visitedBranchPoints="7" sequenceCoverage="22.45" branchCoverage="18.42" maxCyclomaticComplexity="7" minCyclomaticComplexity="1" visitedClasses="4" numClasses="12" visitedMethods="7" numMethods="20" minCrapScore="1" maxCrapScore="16.76" />
...
```

What does the top of the report file look like in your case?

**Comment by IgorBuchelnikov** [comment]
Excuse me, I've executed once again and didn't get any errors.  Possibly I deleted the needed file while executing. Although files should have been locked by altcover and cannot be deleted: I got a corresponding message from MS Windows when tried to delete one of the files.

**Comment by IgorBuchelnikov** [comment]
All coverage files are normal: they have <Summary> record at the top.

**Comment by SteveGilham** [comment]
So, do you have any simple case that reproduces this error, since it's one of those "logically, it can never happen" sort of bugs?

**Comment by IgorBuchelnikov** [comment]
No, this error was one-time, and there were no special conditions (other than deleting files) when the error occurred.

**Comment by SteveGilham** [comment]
In the new [v7.6.812 release](https://www.nuget.org/packages/AltCover/7.6.812), I've changed this code so that it should silently ignore the missing summary (and give no OpenCover-style summary at all)
