### ISSUE TITLE
Failed to resolve assembly while trying to run AltCover on .NET Core

### ISSUE THREAD

**Issue by maciejjarzynski** [SteveGilham/altcover#20]
Hi there,
I am trying to run AltCover on .NET Core 2.0 project (SDK 2.1.4), and I got the following error, either running it via `dotnet test /p:AltCover=true` or via directly calling `AltCover.dll`.

```
Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Cecil.DefaultAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at AltCover.Instrument.WriteAssembly(AssemblyDefinition assembly, String path) in C:\projects\altcover\AltCover\Instrument.fs:line 282
   at AltCover.Instrument.VisitAfterAssembly[a](a state, AssemblyDefinition assembly) in C:\projects\altcover\AltCover\Instrument.fs:line 570
   at AltCover.Instrument.InstrumentationVisitorWrapper(FSharpFunc`2 core, Context state, Node node) in C:\projects\altcover\AltCover\Instrument.fs:line 611
   at AltCover.Visitor.stateful@573-1.Invoke(T node) in C:\projects\altcover\AltCover\Visitor.fs:line 576
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x)
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at AltCover.Visitor.Visit(FSharpList`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 563
   at AltCover.Main.result@330-4.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 344
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 133
AssemblyReference = 
Microsoft.Extensions.DependencyInjection.Abstractions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
FileName = 
<null>
FusionLog = 
<null>
Data = 
seq []
InnerException = 
<null>
TargetSite = 
Mono.Cecil.AssemblyDefinition Resolve(Mono.Cecil.AssemblyNameReference, Mono.Cecil.ReaderParameters)
HelpLink = 
<null>
Source = 
"Mono.Cecil"
HResult = 
-2147024894
```

Is there any fix/workaround for that?

**Comment by SteveGilham** [comment]
This is a Cecil limitation, when there's an indirect reference to a type (e.g. in a method signature as one of the parameter types), it still wants to go out and find the assembly while writing the method out.  With .net core not pulling dependent assemblies into the output folder in the way the classic builds used to, its notion of looking the the GAC or locally fails.

In a previous instance where similar behaviour was reported, it seemed that the problem could be worked around by adding an explicit assembly reference in the affected assembly (the last one named in the stdout messages) to the missing reference (in this case `Microsoft.Extensions.DependencyInjection.Abstractions` ), or so it was reported to me.

**Comment by SteveGilham** [comment]
[Build 3.5.515-pre](https://ci.appveyor.com/project/SteveGilham/altcover/build/artifacts) has a fix, at least one that works for a locally reproduced instance of this type of issue, if you want to give it a try.

**Comment by maciejjarzynski** [comment]
Yup, I confirm that it work now.
Thanks!

**Comment by minuseight** [comment]
Hi, 

We have exactly the same issue running on Windows 10.  Installing the Microsoft.Extensions.DependencyInjection.Abstractions 2.0.0 globally seems to work around the issue.

**Comment by SteveGilham** [comment]
The existing dependency look-up is a simple search through %USERPROFILE%/.nuget when Cecil raises an assembly resolve event.  I wonder if there was a behavioural change in the latest Cecil release.

For the moment, [as per the QuickStart guide](https://github.com/SteveGilham/altcover/wiki/QuickStart-Guide#im-now-getting-altcovertargets-error--failed-to-resolve-assembly-or-altcovertargets-warning--resolved-assembly-reference), using `/p:CopyLocalLockFileAssemblies="true"` on the `dotnet test` command line has the same effect as hard-coding it in your project, but applies for that run only -- that's standard MSBuild behaviour, which can effect a work-around.

For the global tool, the `-d, --dependency=VALUE` command line option to supply and assembly path to resolve missing reference (`/p:AltCoverDependencyList= for the `dotnet test` command line) can be used to supply the exact path for the dependency w/o having to resort to `CopyLocalLockFileAssemblies`.

**Comment by SteveGilham** [comment]
The example I have of this "Cecil wants a reference to a NuGet assembly" runs as expected (simply emits a warning that it has done a fix-up).  

- Do you have a simple repro case you can share?  
- Are you using any of the nuget global-files location overrides as documented at [https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders](https://docs.microsoft.com/en-us/nuget/consume-packages/managing-the-global-packages-and-cache-folders)?

**Comment by SteveGilham** [comment]
Extra question -- which OS are you using?  The could be a file-name casing issue on non-Windows OS's, but that would have been there since the fix-up feature was added back in release 3.5.518

**Comment by SteveGilham** [comment]
I can see why the fixup would fail on Linux -- it seems that the SDK install of the AspNetCore assemblies found under `/usr/share/dotnet/shared/Microsoft.AspNetCore.*` are used in preference to installing any NuGet packages, hence they are not found in a search of the default NuGet global package directory

**Comment by SteveGilham** [comment]
Turns out that the same is true on Windows -- if the files are already under `%ProgramFiles%\dotnet\shared`, they aren't fetched to the NuGet cache.  So, not a regression for the fix-up.

[Pre-release build 650](https://ci.appveyor.com/project/SteveGilham/altcover/builds/19632380/artifacts) has a change to scan the `dotnet/shared` folders (and %NUGET_PACKAGES% if defined) as well as `%USERPROFILE%/.nuget/packages`; if none of those work, that's what the `-d` command line option is for.

**Comment by minuseight** [comment]
We have used the ```-d``` switch on Windows.  I should have read the docs as it's all there.

One quick point if anyone else is reading we had to use an absolute file path with the ```-d``` switch option.

**Comment by SteveGilham** [comment]
A couple of quick notes 
1) build 650 only works on Windows
2) I'll take a look at making relative paths work for `-d` (or rather, finding out why they aren't)

**Comment by SteveGilham** [comment]
The `-d` thing -- I just didn't do the conversion of relative to absolute paths while processing the arguments, expecting it would generally be cut-and-paste from the fix-up. On reflection, that would lock things down to the specific user, which is not so good.  This one could probably benefit from expanding environment variables as well.

**Comment by SteveGilham** [comment]
[Release 4.0.653](https://www.nuget.org/packages/AltCover/4.0.653) should address these issues.

**Comment by nicolasprevot** [comment]
I'm getting a similar error on version 5.3.675 of altcover
Weirdly, it happens only for optional parameters

static void SomeMethod(EnvironmentVariableTarget envTarget = EnvironmentVariableTarget.Machine) {
}

Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.EnvironmentVariableTarget

Target Framework is: netcoreapp2.1

**Comment by SteveGilham** [comment]
@nicolasprevot -- do you have a simple repro of this?  Trying with this 
```
using System;

namespace ConsoleApp3
{
    internal class Helper
    {
        public static void DoIt()
        {
            Helper.SomeMethod();
            Helper.SomeMethod(EnvironmentVariableTarget.Process);
        }

        private static void SomeMethod(EnvironmentVariableTarget envTarget = EnvironmentVariableTarget.Machine)
        {
            Console.WriteLine("Target : '{0}'", envTarget);
        }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Helper.DoIt();
        }
    }
}
```
using the 5.3.675 global tool "just worked" for me.

**Comment by nicolasprevot** [comment]
Sorry for the late reply
From the nuget package altcover at version 5.3.675:
If I launch AltCover from  ./tools/net45/AltCover.exe
Then I get this bug

If I use ./tools/netcoreapp2.0/AltCover.dll
Then it works fine

**Comment by SteveGilham** [comment]
That's because the extra resolution code is currently only compiled into the .net core version.  I suppose there's no harm in adding it to the framework build as well.

**Comment by SteveGilham** [comment]
@nicolasprevot -- the resolution code is in the .net Framework build at release 5.3.679, so should resolve this issue.
