### ISSUE TITLE
FileNotFoundException when running dotnet test on 5.0.663

### ISSUE THREAD

**Issue by maciejjarzynski** [SteveGilham/altcover#48]
When running version `5.0.663` with command   
`dotnet test SolutionName.sln /p:AltCover=true /p:AltCoverAssemblyExcludeFilter="\.Tests" /p:CopyLocalLockFileAssemblies="true" /p:DebugType="pdbonly" /p:AltCoverXmlreport="altcover.xml"` FileNotFoundException errors occur.  
I think it may somehow be related to the change with portable PDBs.

The following error is being logged in the log file:
```
System.IO.FileNotFoundException: Could not find file '/app/*****/Enums.NET.pdb'.
File name: '/app/*****/Enums.NET.pdb'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.Mixin.IsPortablePdb(String fileName)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at AltCover.ProgramDatabase.ReadSymbols@59.Invoke(String pdbpath) in C:\projects\altcover\AltCover\ProgramDatabase.fs:line 65
   at Microsoft.FSharp.Core.OptionModule.Iterate[T](FSharpFunc`2 action, FSharpOption`1 option)
   at AltCover.Visitor.func2@1(AssemblyDefinition x) in C:\projects\altcover\AltCover\Visitor.fs:line 262
   at AltCover.Visitor.StartVisit@248-1.Invoke(String x) in C:\projects\altcover\AltCover\Visitor.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at AltCover.Visitor.Visit(IEnumerable`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 695
   at AltCover.Main.result@426.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 445
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 183
FileName =
"/app/*****/Enums.NET.pdb"
FusionLog =
<null>
Data =
seq []
InnerException =
<null>
TargetSite =
Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
HelpLink =
<null>
Source =
"System.Private.CoreLib"
HResult =
-2147024894
System.IO.FileNotFoundException: Could not find file '/app/*****/Enums.NET.pdb'.
File name: '/app/*****/Enums.NET.pdb'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.Mixin.IsPortablePdb(String fileName)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at AltCover.ProgramDatabase.ReadSymbols@59.Invoke(String pdbpath) in C:\projects\altcover\AltCover\ProgramDatabase.fs:line 65
   at Microsoft.FSharp.Core.OptionModule.Iterate[T](FSharpFunc`2 action, FSharpOption`1 option)
   at AltCover.Visitor.func2@1(AssemblyDefinition x) in C:\projects\altcover\AltCover\Visitor.fs:line 262
   at AltCover.Visitor.StartVisit@248-1.Invoke(String x) in C:\projects\altcover\AltCover\Visitor.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at AltCover.Visitor.Visit(IEnumerable`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 695
   at AltCover.Main.result@426.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 445
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 183
FileName =
"/app/*****/Enums.NET.pdb"
FusionLog =
<null>
Data =
seq []
InnerException =
<null>
TargetSite =
Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
HelpLink =
<null>
Source =
"System.Private.CoreLib"
HResult =
-2147024894
System.IO.FileNotFoundException: Could not find file '/app/*****/System.ComponentModel.Annotations.pdb'.
File name: '/app/*****/System.ComponentModel.Annotations.pdb'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.Mixin.IsPortablePdb(String fileName)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at AltCover.ProgramDatabase.ReadSymbols@59.Invoke(String pdbpath) in C:\projects\altcover\AltCover\ProgramDatabase.fs:line 65
   at Microsoft.FSharp.Core.OptionModule.Iterate[T](FSharpFunc`2 action, FSharpOption`1 option)
   at AltCover.Visitor.func2@1(AssemblyDefinition x) in C:\projects\altcover\AltCover\Visitor.fs:line 262
   at AltCover.Visitor.StartVisit@248-1.Invoke(String x) in C:\projects\altcover\AltCover\Visitor.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at AltCover.Visitor.Visit(IEnumerable`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 695
   at AltCover.Main.result@426.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 445
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 183
FileName =
"/app/*****/System.ComponentModel.Annotations.pdb"
FusionLog =
<null>
Data =
seq []
InnerException =
<null>
TargetSite =
Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
HelpLink =
<null>
Source =
"System.Private.CoreLib"
HResult =
-2147024894
System.IO.FileNotFoundException: Could not find file '/app/*****/System.ComponentModel.Annotations.pdb'.
File name: '/app/*****/System.ComponentModel.Annotations.pdb'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.Mixin.IsPortablePdb(String fileName)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at AltCover.ProgramDatabase.ReadSymbols@59.Invoke(String pdbpath) in C:\projects\altcover\AltCover\ProgramDatabase.fs:line 65
   at Microsoft.FSharp.Core.OptionModule.Iterate[T](FSharpFunc`2 action, FSharpOption`1 option)
   at AltCover.Visitor.func2@1(AssemblyDefinition x) in C:\projects\altcover\AltCover\Visitor.fs:line 262
   at AltCover.Visitor.StartVisit@248-1.Invoke(String x) in C:\projects\altcover\AltCover\Visitor.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at AltCover.Visitor.Visit(IEnumerable`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 695
   at AltCover.Main.result@426.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 445
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 183
FileName =
"/app/*****/System.ComponentModel.Annotations.pdb"
FusionLog =
<null>
Data =
seq []
InnerException =
<null>
TargetSite =
Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
HelpLink =
<null>
Source =
"System.Private.CoreLib"
HResult =
-2147024894
System.IO.FileNotFoundException: Could not find file '/app/*****/System.ComponentModel.Annotations.pdb'.
File name: '/app/*****/System.ComponentModel.Annotations.pdb'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.Mixin.IsPortablePdb(String fileName)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at AltCover.ProgramDatabase.ReadSymbols@59.Invoke(String pdbpath) in C:\projects\altcover\AltCover\ProgramDatabase.fs:line 65
   at Microsoft.FSharp.Core.OptionModule.Iterate[T](FSharpFunc`2 action, FSharpOption`1 option)
   at AltCover.Visitor.func2@1(AssemblyDefinition x) in C:\projects\altcover\AltCover\Visitor.fs:line 262
   at AltCover.Visitor.StartVisit@248-1.Invoke(String x) in C:\projects\altcover\AltCover\Visitor.fs:line 248
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source)
   at AltCover.Visitor.Visit(IEnumerable`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 695
   at AltCover.Main.result@426.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 445
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 183
FileName =
"/app/*****/System.ComponentModel.Annotations.pdb"
FusionLog =
<null>
Data =
seq []
InnerException =
<null>
TargetSite =
Void ThrowExceptionForIoErrno(ErrorInfo, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])
HelpLink =
<null>
Source =
"System.Private.CoreLib"
HResult =
-2147024894
```

`dotnet info` : 

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.502
 Commit:    c74ce8f29f

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.502/

Host (useful for support):
  Version: 2.1.6
  Commit:  3f4f8eebd8

.NET Core SDKs installed:
  2.1.502 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by SteveGilham** [comment]
Looks like portable PDBs to me as well, having already handled a couple of issues similar to this while adding that capability.

**Comment by SteveGilham** [comment]
I have a repro on Windows.  Just including `System.ComponentModel.Annotations.dll` as a reference (rather than through a nuget package) will show this behaviour.  It doesn't repro with 4.0.661, so is indeed a result of the changes for embedded PDBs

**Comment by SteveGilham** [comment]
Addressed in 5.0.664

**Comment by maciejjarzynski** [comment]
Great, I'd check that and give a feedback here.

**Comment by SteveGilham** [comment]
Assuming resolved
