### ISSUE TITLE
AltCover Runner won't run because BlackFox.CommandLine needs binding redirect

### ISSUE THREAD

**Issue by marklam** [SteveGilham/altcover#64]
Trying to use the altcover runner from the nuget package, even with no parameters to the executable:
`C:\Soultion\packages\AltCover\tools\net45\AltCover.exe Runner -r "C:\Solution\Project\bin\Debug\net472\_Instrumented" -x "C:\Solution\packages\NUnit.ConsoleRunner\tools\nunit3-console.exe" `

Throws because the package has a copy of BlackFox.CommandLine.dll which is bound to FSharp.Core 4.4.0.0

```
System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at BlackFox.CommandLine.CmdLine.FromSeq(IEnumerable`1 values)
   at AltCover.CommandLine.ProcessTrailingArguments(FSharpList`1 rest, DirectoryInfo toInfo)
   at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

FileName = 
"FSharp.Core, Version=4.4.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
FusionLog = 
"WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
"
Data = 
seq []
InnerException = 
<null>
TargetSite = 
BlackFox.CommandLine.CmdLine FromSeq(System.Collections.Generic.IEnumerable`1[System.String])
HelpLink = 
<null>
Source = 
"BlackFox.CommandLine"
HResult = 
-2146234304
```

Perhaps it just needs the AltCover.exe.config including in the package?

**Comment by SteveGilham** [comment]
I've not been able to repro this by running the 5.3.675 release from the .nuget cache so I can't be definite about this (not sure what in my environment might be affecting the binding), but yes, it looks like bundling the `app.config` would do the job.

**Comment by SteveGilham** [comment]
The nuget package for release 5.3.679 contains this `app.config` file, so should hopefully resolve this issue.

**Comment by marklam** [comment]
It does fix it -thanks for that quick response!
