### ISSUE TITLE
AltCover breaks .net dependencies ?

### ISSUE THREAD

**Issue by alexey-aurea** [SteveGilham/altcover#66]
Hello @SteveGilham,

I found the following issue (I am not yet sure what is causing it), for some of my test projects running instrumented tests results in the following error:
```
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

At first I assumed there is an issue with the test assembly itself, however running non-instrumented tests were successful.
Here are 2 execution logs to compare:
Non-instrumented run

```
C:\temp>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" "C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\AcornWebServicesTests.dll" /Logger:trx /Platform:x86
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: Using Isolation mode to run the tests as diagnostic data adapters were enabled in the runsettings. Use the /inIsolation parameter to suppress this warning.
Passed   ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle
Passed   IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue
Passed   GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer
Passed   GetConnectionStringFromProductConfig_WhenObjectIsNoValue_ExceptionIsThrown
Passed   GetApplicationServerFromProductConfig_WhenObjectIsNoValue_ExceptionIsThrown
Passed   GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion
Passed   GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName
Passed   GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError
Passed   GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage
Passed   DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue
Passed   DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue
Passed   DoLogin_WhenHasEmptyValues_ExceptionIsThrown
Passed   DoLogin_WhenCoreServiceIsNotNullAndHasEmptyValues_ExceptionIsThrown
Passed   DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue
Passed   DoReLoginNonTrustedUnmapped_WhenNullValues_ExceptionIsThrown
Passed   DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue
Passed   DoLoginNonTrustedUnmapped_WhenNullValues_ExceptionIsThrown
Results File: C:\temp\TestResults\Administrator_WIN-638M0CUH31I 2019-08-15 12_18_58.trx

Total tests: 17. Passed: 17. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 33.1058 Seconds
```

and here is an instrumented run:

```
C:\temp>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\temp\__UnitTestWithAltCover\AcornWebServicesTests.dll /Logger:trx /Platform:x86
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
Warning: Using Isolation mode to run the tests as diagnostic data adapters were enabled in the runsettings. Use the /inIsolation parameter to suppress this warning.
Failed   ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SettingUpLists()
   at AcornWebServicesTests.ServiceHelperTests.ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 73

Failed   IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForIsModelAdmin()
   at AcornWebServicesTests.ServiceHelperTests.IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 91

Failed   GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForProductConfig()
   at AcornWebServicesTests.ServiceHelperTests.GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 104

Passed   GetConnectionStringFromProductConfig_WhenObjectIsNoValue_ExceptionIsThrown
Passed   GetApplicationServerFromProductConfig_WhenObjectIsNoValue_ExceptionIsThrown
Failed   GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForCurrentModelsAndVersions()
   at AcornWebServicesTests.ServiceHelperTests.GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 137

Failed   GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName()

Failed   GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError()

Failed   GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 183

Failed   DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 196

Failed   DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForCoreServiceIsNull()
   at AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 209

Passed   DoLogin_WhenHasEmptyValues_ExceptionIsThrown
Passed   DoLogin_WhenCoreServiceIsNotNullAndHasEmptyValues_ExceptionIsThrown
Failed   DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 244

Passed   DoReLoginNonTrustedUnmapped_WhenNullValues_ExceptionIsThrown
Failed   DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 267

Passed   DoLoginNonTrustedUnmapped_WhenNullValues_ExceptionIsThrown
Results File: C:\temp\TestResults\Administrator_WIN-638M0CUH31I 2019-08-15 12_19_49.trx

Total tests: 17. Passed: 6. Failed: 11. Skipped: 0.
Test Run Failed.
Test execution time: 21.4707 Seconds
```

Here is a full invocation log of the altCover:

```
C:\temp>C:\temp\altCover\tools\net45\AltCover.exe /i=C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\ /o="C:\temp\__UnitTestWithAltCover" -s=Microsoft. -s=nunit -s=nlog -s=System. -s=ShinerResources  -s=Moq -s=UnitTestLibrary -s=Shouldly -s=Blacklight -s=\.Fakes -s=\.Test -s=\.Tests -s=Fluent -s=ClosedXML -s=Silverlight /x="ALTCOVER_VSTEST_AcornWebServicesTests.dll.xml" --opencover -- "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\temp\__UnitTestWithAltCover\AcornWebServicesTests.dll /Logger:trx /Platform:x86
Instrumenting files from C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\
Writing files to C:\temp\__UnitTestWithAltCover
   => C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\AAA.Acornsys.AcornCore.dll
   => C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\AAA.Acornsys.WebServices.dll
   => C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\AcornWebServicesTests.dll
   => C:\work\develop-AAA\AcornWebServicesTests\bin\Debug\UtilityLibrary.dll

Coverage Report: C:\temp\ALTCOVER_VSTEST_AcornWebServicesTests.dll.xml


    C:\temp\__UnitTestWithAltCover\UtilityLibrary.dll
                <=  UtilityLibrary, Version=2019.1.0.0, Culture=neutral, PublicKeyToken=null
    C:\temp\__UnitTestWithAltCover\AAA.Acornsys.AcornCore.dll
                <=  AAA.Acornsys.AcornCore, Version=2019.1.0.0, Culture=neutral, PublicKeyToken=null
    C:\temp\__UnitTestWithAltCover\AAA.Acornsys.WebServices.dll
                <=  AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=null
    C:\temp\__UnitTestWithAltCover\AcornWebServicesTests.dll
                <=  AcornWebServicesTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Command line : '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\temp\__UnitTestWithAltCover\AcornWebServicesTests.dll /Logger:trx /Platform:x86'
Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
Warning: Using Isolation mode to run the tests as diagnostic data adapters were enabled in the runsettings. Use the /inIsolation parameter to suppress this warning.
Failed   ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SettingUpLists()
   at AcornWebServicesTests.ServiceHelperTests.ExtractReportTitle_WhenEntityNameAndReportTitleAreEqual_ResultContainsTitle() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 73
Failed   IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue threw exception:
Failed   GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForIsModelAdmin()
   at AcornWebServicesTests.ServiceHelperTests.IsModelAdmin_WhenPrivilegesNameIsEqual_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 91
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForProductConfig()
   at AcornWebServicesTests.ServiceHelperTests.GetApplicationServerFromProductConfig_WhenRemotePortIsNotEmpty_ResultContainsAppServer() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 104
Passed   GetConnectionStringFromProductConfig_WhenObjectIsNoValue_ExceptionIsThrown
Error Message:
Passed   GetApplicationServerFromProductConfig_WhenObjectIsNoValue_ExceptionIsThrown
   Test method AcornWebServicesTests.ServiceHelperTests.GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion threw exception:
Failed   GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion
Failed   GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Failed   GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError
Failed   GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage
Stack Trace:
Failed   DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForCurrentModelsAndVersions()
Failed   DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue
   at AcornWebServicesTests.ServiceHelperTests.GetCurrentModelAndVersion_WhenModelReturnIsNull_ResultHasCurrentModelVersion() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 137
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportHasValidResult_ResultContainsTableName()
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenReportDoesNotHaveValidResult_ResultContainsError()
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.GetFilterTableName_WhenNoDataService_ResultContainsErrorMessage() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 183
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNotNullAndConnectionIsTrusted_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 196
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.ArrangeForCoreServiceIsNull()
   at AcornWebServicesTests.ServiceHelperTests.DoLogin_WhenCoreServiceIsNullAndConnectionIsTrusted_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 209
Passed   DoLogin_WhenHasEmptyValues_ExceptionIsThrown
Error Message:
Passed   DoLogin_WhenCoreServiceIsNotNullAndHasEmptyValues_ExceptionIsThrown
   Test method AcornWebServicesTests.ServiceHelperTests.DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue threw exception:
Failed   DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Passed   DoReLoginNonTrustedUnmapped_WhenNullValues_ExceptionIsThrown
Stack Trace:
Failed   DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.DoReLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 244
Error Message:
   Test method AcornWebServicesTests.ServiceHelperTests.DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue threw exception:
System.IO.FileLoadException: Could not load file or assembly 'AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Stack Trace:
    at AcornWebServicesTests.ServiceHelperTests.SetupShims()
   at AcornWebServicesTests.ServiceHelperTests.DoLoginNonTrustedUnmapped_WhenTotalSecondsAreLessThenAfterSeconds_ResultIsTrue() in C:\work\develop-AAA\AcornWebServicesTests\ServiceHelperTests.cs:line 267
Passed   DoLoginNonTrustedUnmapped_WhenNullValues_ExceptionIsThrown
^CTerminate batch job (Y/N)? Y
```

Running tests without /Platform:x86 key gives same 'System.IO.FileLoadException'. Is there a chance this issue can be fixed by enabling some altCover flags ?

**Comment by SteveGilham** [comment]
This is something I hit myself [a couple of months back](https://github.com/SteveGilham/altcover/commit/b1c67e15f5fd7f89f72d49d3e73dd960c6917b6e); fortunately the log provides sufficient information for diagnosis.

The code is looking for an assembly called `AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=d63bc43be01c8648`.  This specificity is usually in response to something that has baked in references to assembly-qualified types -- this can happen for some serialization mechanisms, for example, or some uses of F# quotations, which sort-of serialize under the covers.

However, the output instrumented assembly is reported as `AAA.Acornsys.WebServices, Version=19.1.0.0, Culture=neutral, PublicKeyToken=null`; the instrumentation process hasn't been given a key for strong-naming the newly minted assemblies.

You need to take advantage of the

*  --sn, --strongNameKey=VALUE Optional: The default strong naming key to apply to instrumented assemblies (default: None)

option to feed in the same key as used to strong-name the original assembly, so that the instrumented assembly will have the strong-name to match, thus satisfying whatever is looking for the assembly by full name.

**Comment by alexey-aurea** [comment]
But does this mean that I have to sign all my libraries with the strong keys before I feed them to the altCover ?

**Comment by SteveGilham** [comment]
You don't in general need to strong-name files in order to gain coverage data.  Only in cases, like this one, where having done so in the build, that fact then gets baked in by some mechanism (usually serialization).  In such circumstances, you will need to propagate the as-built strong-naming into the instrumented assemblies.

As the tests here are called `AcornWebServicesTests`, I'm making the assumption that all the `AAA.Acornsys.*` files are ones that you are building; and as something in the system is making the statement that `AAA.Acornsys.WebServices.dll` is strong-named, by fact of having reference to a full assembly name with a non-null `PublicKeyToken`, that you are already strong-naming them.  

Given that assumption, all that is required is to pass the path to the current `.snk` file that you must be already using as part of the build to the AltCover step either as a `--sn` argument (strong-name everything with this key) or a `-k` argument (strong-name those assemblies that previously used this key).
